upstream solusiku {
  server php1:9000;
#  server 10.99.99.253 backup;
#  server 127.0.0.1 backup; #jika server utama down maka server ini yg akan online
}
server {
    listen 80;
    server_name solusiku.my.id;
    index index.php index.html;
    root /var/www/public;

    client_max_body_size 500M; 

    location / {
        root /var/www/public;
        index index.html index.php;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # fastcgi_pass solusiku;
        # fastcgi_pass php_backend;
          fastcgi_pass php1:9000;
        # proxy_pass http://haproxy:9000;
        # fastcgi_pass haproxy:9000
        fastcgi_read_timeout 3600;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        # fastcgi_param PHP_SERVER_NAME $upstream_addr;
        send_timeout 3600;
        proxy_connect_timeout 3600;
        proxy_read_timeout    3600;
        proxy_send_timeout    3600;
    }
}
