server {
    listen 80;
    server_name dataku.my.id;
    # return 301 https://$host$request_uri;
}

upstream dataku {
  server php2:9000;
#  server 10.99.99.253 backup;
#  server 127.0.0.1 backup; #jika server utama down maka server ini yg akan online
}

server {

    listen 80;
    server_name dataku.my.id;

    # ssl_certificate           /etc/letsencrypt/live/logbooks.unri.ac.id/fullchain.pem;
    # ssl_certificate_key       /etc/letsencrypt/live/logbooks.unri.ac.id/privkey.pem;

    # ssl on;
    # ssl_session_cache  builtin:1000  shared:SSL:10m;
    # ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    # ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    # ssl_prefer_server_ciphers on;

    # access_log            /var/log/nginx/access.logbooks.unri.ac.id.log;
    # error_log            /var/log/nginx/error.logbooks.unri.ac.id.log;

  location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          http://dataku;
      # fastcgi_pass dataku 
      proxy_read_timeout  90;

    #   proxy_redirect      http://route-logbooks https://logbooks.unri.ac.id;
    }
  }

# server {
#     listen 10.99.99.253:8080;
#     server_name logbooks.unri.ac.id;
#     location / {
#         proxy_pass http://127.0.0.1;
#         }
# }

